version: '3.8'
services:
  app:
    build:
      context: './'
      dockerfile: ./Dockerfile
    container_name: tiny_efrei_dev__app
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    networks:
      - redis_net
    depends_on:
      - redis

  redis:
    hostname: redis
    container_name: tiny_efrei_dev__redis
    image: redis:alpine
    expose:
      - 6379
    networks:
      - redis_net
    volumes:
      - redis_data:/data

networks:
  redis_net:

volumes:
  redis_data:
